"""item comments

Revision ID: 0249101dc267
Revises: 1e58e0d50c01
Create Date: 2026-07-31 17:46:57.326953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0249101dc267'
down_revision: Union[str, Sequence[str], None] = '1e58e0d50c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_comments_ip'), ['ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_comments_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_comments_restaurant_id'), ['restaurant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_comments_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_item_comments_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_comments_ip'))

    op.drop_table('item_comments')
    # ### end Alembic commands ###
