"""wifi, dietary markers and specials

Revision ID: 1e58e0d50c01
Revises: 8707209aa810
Create Date: 2026-07-31 17:39:20.142995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e58e0d50c01'
down_revision: Union[str, Sequence[str], None] = '8707209aa810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


I18N = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    """Upgrade schema."""
    # server_default bo'lmasa mavjud taomlarda NOT NULL buziladi
    with op.batch_alter_table("menu_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("allergens", I18N, nullable=False, server_default="{}")
        )
        for flag in ("is_special", "is_spicy", "is_vegetarian", "is_halal"):
            batch_op.add_column(
                sa.Column(flag, sa.Boolean(), nullable=False, server_default=sa.false())
            )

    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("wifi_name", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("wifi_password", sa.String(length=64), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('wifi_password')
        batch_op.drop_column('wifi_name')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_halal')
        batch_op.drop_column('is_vegetarian')
        batch_op.drop_column('is_spicy')
        batch_op.drop_column('is_special')
        batch_op.drop_column('allergens')

    # ### end Alembic commands ###
