"""add login attempts and menu views

Revision ID: 7f03be16655b
Revises: 4009b2b96973
Create Date: 2026-07-31 11:17:56.149222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f03be16655b'
down_revision: Union[str, Sequence[str], None] = '4009b2b96973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)

    op.create_table('menu_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'item_id', 'day', name='uq_menu_views_day')
    )
    with op.batch_alter_table('menu_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_views_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_views_restaurant_id'), ['restaurant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_views_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_menu_views_day'))

    op.drop_table('menu_views')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
