"""add plans and subscription

Revision ID: cfc6216f7469
Revises: 125f96680adf
Create Date: 2026-07-31 11:49:11.829900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc6216f7469'
down_revision: Union[str, Sequence[str], None] = '125f96680adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    plan = sa.Enum("free", "standard", "premium", name="plan", native_enum=False)
    status = sa.Enum(
        "trial", "active", "expired", name="subscriptionstatus", native_enum=False
    )

    # server_default bo'lmasa mavjud qatorlarda NOT NULL buziladi
    with op.batch_alter_table("restaurants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("plan", plan, nullable=False, server_default="free")
        )
        batch_op.add_column(
            sa.Column(
                "subscription_status", status, nullable=False, server_default="trial"
            )
        )
        batch_op.add_column(sa.Column("trial_ends_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("paid_until", sa.DateTime(), nullable=True))

    # Tariflar joriy qilinishidan oldin mavjud bo'lgan restoranlar qo'lda ulangan —
    # ularni cheklovga tushirib qo'ymaymiz, to'liq imkoniyat bilan qoldiramiz
    op.execute(
        "UPDATE restaurants SET plan = 'premium', subscription_status = 'active'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('paid_until')
        batch_op.drop_column('trial_ends_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
